//Level,Name,																																		Experience,	Time,	Favor,	Location,							Adventure Pack,					Damage Reduction Types,																																									Notes,	Completed
var raw_Table_String = 
"1		<a href=\"http://ddowiki.com/page/The_Collaborator\">The Collaborator</a>																	0	1				12		Korthos								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
1		<a href=\"http://ddowiki.com/page/Redemption_(quest)\">Redemption</a>																		0	1				9		Korthos								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
1		<a href=\"http://ddowiki.com/page/Sacrifices\">Sacrifices</a>																				0	1				9		Korthos								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
1		<a href=\"http://ddowiki.com/page/Stopping_the_Sahuagin\">Stopping the Sahuagin</a>															0	1				9		Korthos								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
1		<a href=\"http://ddowiki.com/page/Heyton%27s_Rest\">Heyton\'s Rest</a>																		0	1				6		Korthos								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
1		<a href=\"http://ddowiki.com/page/Necromancer%27s_Doom\">Necromancer\'s Doom</a>															0	1				6		Korthos								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
1		<a href=\"http://ddowiki.com/page/The_Cannith_Crystal\">The Cannith Crystal</a>																0	1				6		Korthos								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
1		<a href=\"http://ddowiki.com/page/The_Storehouse%27s_Secret\">The Storehouse\'s Secret</a>													0	1				6		Korthos								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Durk%27s_Got_a_Secret\">Durk\'s Got a Secret</a>															0	1				12		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Garrison%27s_Missing_Pack\">Garrison\'s Missing Pack</a>													0	1				12		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Information_is_Key\">Information is Key</a>																0	1				12		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/The_Kobolds%27_New_Ringleader\">The Kobolds\' New Ringleader</a>											0	1				12		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Walk_the_Butcher%27s_Path\">Walk the Butcher\'s Path</a>													0	1				12		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Recovering_the_Lost_Tome\">Recovering the Lost Tome</a>													0	1				9		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Retrieve_the_Stolen_Goods\">Retrieve the Stolen Goods</a>													0	1				9		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Stealthy_Repossession\">Stealthy Repossession</a>															0	1				9		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/The_Smuggler%27s_Warehouse\">The Smuggler\'s Warehouse</a>												0	1				9		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Bringing_the_Light\">Bringing the Light</a>																0	1				6		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Haverdasher\">Haverdasher</a>																				0	1				6		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Protect_Baudry%27s_Interests\">Protect Baudry\'s Interests</a>											0	1				6		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Stop_Hazadill%27s_Shipment\">Stop Hazadill\'s Shipment</a>												0	1				6		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Arachnophobia\">Arachnophobia</a>																			0	1				2		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/The_Miller%27s_Debt\">The Miller\'s Debt</a>																0	1				2		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Misery%27s_Peak\">Misery\'s Peak</a>																		0	1				12		Korthos								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/Missing_in_Action\">Missing in Action</a>																	0	1				9		Marketplace							Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
2		<a href=\"http://ddowiki.com/page/The_Sunken_Sewer\">The Sunken Sewer</a>																	0	1				9		Marketplace							Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/Kobold_Assault\">Kobold Assault</a>																		0	1				9		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/An_Explosive_Situation\">An Explosive Situation</a>														0	1				2		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/Home_Sweet_Sewer\">Home Sweet Sewer</a>																	0	1				2		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Captives\">The Captives</a>																			0	1				9		Harbor - Cerulean Hills				Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/Where_There%27s_Smoke...\">Where There\'s Smoke...</a>													0	1				9		Harbor - Cerulean Hills				Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Kobold%27s_Den:_Clan_Gnashtooth\">The Kobold\'s Den: Clan Gnashtooth</a>								0	1				12		Harbor - The Waterworks				Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Kobold%27s_Den:_Rescuing_Arlos\">The Kobold\'s Den: Rescuing Arlos</a>								0	1				12		Harbor - The Waterworks				Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/First_Strike\">First Strike</a>																			0	1				9		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Hobgoblins%27_Captives\">The Hobgoblins\' Captives</a>												0	1				9		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/Redfang_the_Unruled\">Redfang the Unruled</a>																0	1				9		Marketlace							Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Swiped_Signet\">The Swiped Signet</a>																	0	1				12		Marketplace							Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Cloven-jaw_Scourge:_Blockade\">The Cloven-jaw Scourge: Blockade</a>									0	1				12		Marketplace - Steam Tunnels			The Seal of Shan-To-Kor			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Sacred_Helm\">The Sacred Helm</a>																		0	1				12		Marketplace - Steam Tunnels			The Seal of Shan-To-Kor			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Crypt_of_Gerard_Dryden\">The Crypt of Gerard Dryden</a>												0	1				12		Marketplace - The Catacombs			The Catacombs					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/Setting_the_Wards:_The_Lower_Cathedral\">Setting the Wards: The Lower Cathedral</a>						0	1				9		Marketplace - The Catacombs			The Catacombs					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/Setting_the_Wards:_The_Patriarchs%27_Crypt\">Setting the Wards: The Patriarchs\' Crypt</a>				0	1				9		Marketplace - The Catacombs			The Catacombs					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Old_Archives\">The Old Archives</a>																	0	1				9		Marketplace - The Catacombs			The Catacombs					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/To_Find_a_Witness:_Return_to_the_Sanctuary\">To Find a Witness: Return to the Sanctuary</a>				0	1				9		Marketplace - The Catacombs			The Catacombs					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/Endgame:_Marguerite\">Endgame: Marguerite</a>																0	1				6		Marketplace - The Catacombs			The Catacombs					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
3		<a href=\"http://ddowiki.com/page/The_Friar%27s_Niece\">The Friar\'s Niece</a>																0	1				6		Marketplace - The Catacombs			The Catacombs					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Irestone_Inlet\">Irestone Inlet</a>																		0	1				12		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Venn%27s_Trail:_Clan_Tunnelworm\">Venn\'s Trail: Clan Tunnelworm</a>										0	1				12		Harbor - Waterworks					Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Venn%27s_Trail:_Venn%27s_Fate\">Venn\'s Trail: Venn\'s Fate</a>											0	1				9		Harbor - Waterworks					Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/The_Depths_of_Darkness\">The Depths of Darkness</a>														0	1				9		House Deneith						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/The_Depths_of_Despair\">The Depths of Despair</a>															0	1				9		House Deneith						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Rest_for_the_Restless\">Rest for the Restless</a>															0	1				9		House Phiarlan						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Whisperdoom%27s_Spawn\">Whisperdoom\'s Spawn</a>															0	1				9		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Yarkuch%27s_War-plans\">Yarkuch\'s War-plans</a>															0	1				9		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Proof_is_in_the_Poison\">Proof is in the Poison</a>														0	1				15		Marketplace							Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Freshen_the_Air\">Freshen the Air</a>																		0	1				9		Marketplace							Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Come_Out_and_Slay\">Come Out and Slay</a>																	0	1				6		Marketplace							The Sharn Syndicate				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Dirty_Laundry\">Dirty Laundry</a>																			0	1				6		Marketplace							The Sharn Syndicate				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Repossession\">Repossession</a>																			0	1				6		Marketplace							The Sharn Syndicate				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Stand_Your_Ground\">Stand Your Ground</a>																	0	1				6		Marketplace							The Sharn Syndicate				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/The_Bookbinder_Rescue\">The Bookbinder Rescue</a>															0	1				6		Marketplace							The Sharn Syndicate				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/The_Stormreaver_Fresco\">The Stormreaver Fresco</a>														0	1				6		Marketplace							The Sharn Syndicate				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/The_Cloven-jaw_Scourge:_The_Caverns_of_Shaagh\">The Cloven-jaw Scourge: The Caverns of Shaagh</a>			0	1				12		Marketplace - Steam Tunnels			The Seal of Shan-To-Kor			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
4		<a href=\"http://ddowiki.com/page/Endgame:_The_Archbishop%27s_Fate\">Endgame: The Archbishop\'s Fate</a>									0	1				6		Marketplace - The Catacombs			The Catacombs					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/The_Chamber_of_Insanity\">The Chamber of Insanity</a>														0	1				9		House Deneith						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/The_Depths_of_Discord\">The Depths of Discord</a>															0	1				9		House Deneith						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/The_Depths_of_Doom\">The Depths of Doom</a>																0	1				9		House Deneith						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/The_Mystery_of_Delera%27s_Tomb\">The Mystery of Delera\'s Tomb</a>										0	1				12		House Jorasco - Delera\'s Tomb		Delera\'s Tomb					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/The_Lair_of_Summoning\">The Lair of Summoning</a>															0	1				9		House Kundarak						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/A_Small_Problem\">A Small Problem</a>																		0	1				12		House Phiarlan						Phiarlan Carnival				-																																														Has Epic version	<input type=\"checkbox\">\n\
5		<a href=\"http://ddowiki.com/page/Partycrashers\">Partycrashers</a>																			0	1				12		House Phiarlan						Phiarlan Carnival				-																																														Has Epic version	<input type=\"checkbox\">\n\
5		<a href=\"http://ddowiki.com/page/The_Snitch\">The Snitch</a>																				0	1				12		House Phiarlan						Phiarlan Carnival				-																																														Has Epic version	<input type=\"checkbox\">\n\
5		<a href=\"http://ddowiki.com/page/Under_the_Big_Top\">Under the Big Top</a>																	0	1				12		House Phiarlan						Phiarlan Carnival				-																																														Has Epic version	<input type=\"checkbox\">\n\
5		<a href=\"http://ddowiki.com/page/The_Deadly_Package:_Agent_of_the_Darguul\">The Deadly Package: Agent of the Darguul</a>					0	1				9		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/The_Deadly_Package:_The_Stronghold_Key\">The Deadly Package: The Stronghold Key</a>						0	1				9		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/Tomb_of_the_Crimson_Heart\">Tomb of the Crimson Heart</a>													0	1				12		House Phiarlan - The Necropolis		The Necropolis, Part 1			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/Tomb_of_the_Immortal_Heart\">Tomb of the Immortal Heart</a>												0	1				12		House Phiarlan - The Necropolis		The Necropolis, Part 1			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/Tomb_of_the_Sanguine_Heart\">Tomb of the Sanguine Heart</a>												0	1				12		House Phiarlan - The Necropolis		The Necropolis, Part 1			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/Tomb_of_the_Burning_Heart\">Tomb of the Burning Heart</a>													0	1				9		House Phiarlan - The Necropolis		The Necropolis, Part 1			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/Archer_Point_Defense\">Archer Point Defense</a>															0	1				9		Marketplace							Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/Halls_of_Shan-To-Kor\">Halls of Shan-To-Kor</a>															0	1				12		Marketplace - Steam Tunnels			The Seal of Shan-To-Kor			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/Ghost_of_a_Chance\">Ghost of a Chance</a>																	0	1				12		Three-Barrel Cove					Three-Barrel Cove				-																																														Has Epic version	<input type=\"checkbox\">\n\
5		<a href=\"http://ddowiki.com/page/Legend_of_Two-Toed_Tobias\">Legend of Two-Toed Tobias</a>													0	1				12		Three-Barrel Cove					Three-Barrel Cove				-																																														Has Epic version	<input type=\"checkbox\">\n\
5		<a href=\"http://ddowiki.com/page/Prove_Your_Worth\">Prove Your Worth</a>																	0	1				12		Three-Barrel Cove					Three-Barrel Cove				-																																														Has Epic version	<input type=\"checkbox\">\n\
5		<a href=\"http://ddowiki.com/page/The_Stones_Run_Red\">The Stones Run Red</a>																0	1				12		Three-Barrel Cove					Three-Barrel Cove				-																																														Has Epic version	<input type=\"checkbox\">\n\
5		<a href=\"http://ddowiki.com/page/Brood_of_Flame\">Brood of Flame</a>																		0	1				9		Three-Barrel Cove					Three-Barrel Cove				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
5		<a href=\"http://ddowiki.com/page/Guard_Duty\">Guard Duty</a>																				0	1				9		Three-Barrel Cove					Three-Barrel Cove				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/The_Bounty_Hunter\">The Bounty Hunter</a>																	0	1				15		House Deneith						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/The_Iron_Mines:_Justice_for_Grust\">The Iron Mines: Justice for Grust</a>									0	1				12		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/The_Iron_Mines:_Freeing_Achka\">The Iron Mines: Freeing Achka</a>											0	1				9		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Redwillow%27s_Ruins\">Redwillow\'s Ruins</a>																0	1				15		House Jorasco						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Dead_Predators\">Dead Predators</a>																		0	1				12		House Jorasco						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Mirra%27s_Sleepless_Nights\">Mirra\'s Sleepless Nights</a>												0	1				12		House Jorasco						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Valak%27s_Mausoleum\">Valak\'s Mausoleum / Dead Girl\'s Spellbook</a>										0	1				12		House Jorasco - Delera\'s Tomb		Delera\'s Tomb					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Return_to_Delera%27s_Tomb_(Quest)\">Return to Delera\'s Tomb</a>											0	1				9		House Jorasco - Delera\'s Tomb		Delera\'s Tomb					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Ruined_Halls\">Ruined Halls</a>																			0	1				12		House Kundarak						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/The_Forgotten_Caverns\">The Forgotten Caverns</a>															0	1				12		House Kundarak						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Caged_Trolls\">Caged Trolls</a>																			0	1				12		House Phiarlan						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Purge_the_Heretics\">Purge the Heretics</a>																0	1				12		House Phiarlan						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Doom_of_the_Witch-doctor:_The_Way_to_Zulkash\">Doom of the Witch-doctor: The Way to Zulkash</a>			0	1				12		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Doom_of_the_Witch-doctor:_Zulkash,_Herald_of_Woe\">Doom of the Witch-doctor: Zulkash, Herald of Woe</a>	0	1				12		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/The_Bloody_Crypt\">The Bloody Crypt</a>																	0	16				21		House Phiarlan - The Necropolis		The Necropolis, Part 1			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/Gladewatch_Outpost_Defense\">Gladewatch Outpost Defense</a>												0	1				12		Marketplace							Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
6		<a href=\"http://ddowiki.com/page/The_Troglodytes%27_Get\">The Troglodytes\' Get</a>														0	1				12		Three-Barrel Cove					Three-Barrel Cove				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/The_Pit\">The Pit</a>																						0	1				27		House Deneith						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/The_Grey_Moon%27s_Den:_Extermination\">The Grey Moon\'s Den: Extermination</a>							0	1				12		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/The_Grey_Moon%27s_Den:_The_Trollish_Scourge\">The Grey Moon\'s Den: The Trollish Scourge</a>				0	1				12		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/The_Graverobber\">The Graverobber</a>																		0	1				15		House Jorasco						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/The_Missing_Party\">The Missing Party</a>																	0	1				18		House Jorasco - Delera\'s Tomb		Delera\'s Tomb					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/Free_Delera\">Free Delera</a>																				0	1				15		House Jorasco - Delera\'s Tomb		Delera\'s Tomb					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/Taming_the_Flames\">Taming the Flames</a>																	0	1				15		House Kundarak						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/The_Tear_of_Dhakaan\">The Tear of Dhakaan</a>																0	1				21		House Phiarlan						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/Gwylan%27s_Stand\">Gwylan\'s Stand</a>																	0	1				18		House Phiarlan						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/The_Last_Move:_Yarkuch%27s_Last_Stand\">The Last Move: Yarkuch\'s Last Stand</a>							0	1				12		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/The_Last_Move:_The_Way_to_Yarkuch\">The Last Move: The Way to Yarkuch</a>									0	1				9		House Phiarlan - Tangleroot Gorge	Tangleroot Gorge				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
7		<a href=\"http://ddowiki.com/page/Old_Grey_Garl\">Old Grey Garl</a>																			0	1				15		Three-Barrel Cove					Three-Barrel Cove				-																																														Has Epic version	<input type=\"checkbox\">\n\
7		<a href=\"http://ddowiki.com/page/The_Scoundrel%27s_Run\">The Scoundrel\'s Run</a>															0	1				12		Three-Barrel Cove					Three-Barrel Cove				-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Assault_on_the_Aerie_of_the_Slave_Lords\">Assault on the Aerie of the Slave Lords</a>						0	1				15		Hall of Heroes						Against the Slave Lords			-																																														Has Epic version	<input type=\"checkbox\">\n\
8		<a href=\"http://ddowiki.com/page/Secret_of_the_Slavers%27_Stockade\">Secret of the Slavers\' Stockade</a>									0	1				15		Hall of Heroes						Against the Slave Lords			-																																														Has Epic version	<input type=\"checkbox\">\n\
8		<a href=\"http://ddowiki.com/page/Slave_Pits_of_the_Undercity\">Slave Pits of the Undercity</a>												0	1				15		Hall of Heroes						Against the Slave Lords			-																																														Has Epic version	<input type=\"checkbox\">\n\
8		<a href=\"http://ddowiki.com/page/Stormcleave_Outpost\">Stormcleave Outpost</a>																0	1				18		House Deneith						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Stromvauld%27s_Mine\">Stromvauld\'s Mine</a>																0	1				15		House Deneith						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/The_Temple_Outpost:_Captives_of_the_Cult\">The Temple Outpost: Captives of the Cult</a>					0	1				12		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/The_Temple_Outpost:_The_Libram_of_the_Six\">The Temple Outpost: The Libram of the Six</a>					0	1				12		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/The_Xorian_Cipher\">The Xorian Cipher</a>																	0	1				21		House Jorasco						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Haunted_Library\">Haunted Library</a>																		0	1				15		House Jorasco						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/The_Path_to_Madness\">The Path to Madness</a>																0	1				9		House Jorasco						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Thrall_of_the_Necromancer\">Thrall of the Necromancer</a>													0	1				18		House Jorasco - Delera\'s Tomb		Delera\'s Tomb					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Caverns_of_Korromar\">Caverns of Korromar</a>																0	1				15		House Kundarak						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Tharashk_Arena\">Tharashk Arena</a>																		0	1				15		House Kundarak						The Vault of Night				-																																														Has Epic version	<input type=\"checkbox\">\n\
8		<a href=\"http://ddowiki.com/page/The_Prisoner\">The Prisoner</a>																			0	1				15		House Kundarak						The Vault of Night				-																																														Has Epic version	<input type=\"checkbox\">\n\
8		<a href=\"http://ddowiki.com/page/The_Faithful_Departed\">Faithful Departed</a>																0	1				12		House Phiarlan						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Tomb_of_the_Shadow_Guard\">Tomb of the Shadow Guard</a>													0	12				15		House Phiarlan - The Necropolis		The Necropolis, Part 2			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Tomb_of_the_Shadow_King\">Tomb of the Shadow King</a>														0	11				15		House Phiarlan - The Necropolis		The Necropolis, Part 2			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Tomb_of_the_Shadow_Knight\">Tomb of the Shadow Knight</a>													0	1				15		House Phiarlan - The Necropolis		The Necropolis, Part 2			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/Tomb_of_the_Shadow_Lord\">Tomb of the Shadow Lord</a>														0	18				15		House Phiarlan - The Necropolis		The Necropolis, Part 2			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/The_Rescue\">The Rescue</a>																				0	1				15		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
8		<a href=\"http://ddowiki.com/page/In_Need_of_Supplies\">In Need of Supplies</a>																0	1				9		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
9		<a href=\"http://ddowiki.com/page/The_Fane_of_the_Six:_Cleansing_the_Temple\">The Fane of the Six: Cleansing the Temple</a>					0	1				12		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
9		<a href=\"http://ddowiki.com/page/The_Fane_of_the_Six:_Fall_of_the_Prelate\">The Fane of the Six: Fall of the Prelate</a>					0	1				12		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
9		<a href=\"http://ddowiki.com/page/The_Keeper%27s_Sanctuary\">The Keeper\'s Sanctuary</a>													0	1				12		House Jorasco - Delera\'s Tomb		Delera\'s Tomb					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
9		<a href=\"http://ddowiki.com/page/The_Jungle_of_Khyber\">The Jungle of Khyber</a>															0	1				27		House Kundarak						The Vault of Night				-																																														Has Epic version	<input type=\"checkbox\">\n\
9		<a href=\"http://ddowiki.com/page/Haywire_Foundry\">Haywire Foundry</a>																		0	1				18		House Kundarak						The Vault of Night				-																																														Has Epic version	<input type=\"checkbox\">\n\
9		<a href=\"http://ddowiki.com/page/Gateway_to_Khyber\">Gateway to Khyber</a>																	0	1				9		House Kundarak						The Vault of Night				-																																														-	<input type=\"checkbox\">\n\
9		<a href=\"http://ddowiki.com/page/The_Church_and_the_Cult\">The Church and the Cult</a>														0	1				15		House Phiarlan						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
9		<a href=\"http://ddowiki.com/page/The_Shadow_Crypt\">The Shadow Crypt</a>																	0	15				21		House Phiarlan - The Necropolis		The Necropolis, Part 2			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
9		<a href=\"http://ddowiki.com/page/Entering_the_Gate_Chamber\">Entering the Gate Chamber</a>													0	1				15		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
9		<a href=\"http://ddowiki.com/page/The_Missing_Expedition\">The Missing Expedition</a>														0	1				12		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
9		<a href=\"http://ddowiki.com/page/The_Library_of_Threnal\">The Library of Threnal</a>														0	1				9		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
9		<a href=\"http://ddowiki.com/page/The_Giant_Lieutenants\">The Giant Lieutenants</a>															0	1				0		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\">\n\
9		<a href=\"http://ddowiki.com/page/The_Giants%27_Lair\">The Giants\' Lair</a>																0	1				0		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\">\n\
10		<a href=\"http://ddowiki.com/page/Reclamation\">Reclamation</a>																				0	1				15		Ataraxia\'s Haven					Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/Sykros%27_Jewel\">Sykros\' Jewel</a>																		0	1				15		Ataraxia\'s Haven					Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/Hiding_in_Plain_Sight\">Hiding in Plain Sight</a>															0	1				15		Harbor								Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/The_Sanctum:_Church_of_the_Fury\">The Sanctum: Church of the Fury</a>										0	1				12		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/The_Sanctum:_Quench_the_Flames\">The Sanctum: Quench the Flames</a>										0	1				12		House Deneith - Sorrowdusk Isle		Sorrowdusk Isle					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/Tempest%27s_Spine\">Tempest\'s Spine</a>																	0	1				18		House Jorasco						Free to Play					-																																														Raid- no timer	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/The_Vault_of_Night\">The Vault of Night</a>																0	1				27		House Kundarak						The Vault of Night				-																																														Has Epic version	<input type=\"checkbox\">\n\
10		<a href=\"http://ddowiki.com/page/Plane_of_Night\">Plane of Night</a>																		0	1				15		House Kundarak						The Vault of Night				-																																														Has Epic version	<input type=\"checkbox\">\n\
10		<a href=\"http://ddowiki.com/page/Escort_the_Expedition\">Escort the Expedition</a>															0	1				18		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/Secure_the_Area\">Secure the Area</a>																		0	1				12		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/Hold_for_Reinforcements\">Hold for Reinforcements</a>														0	1				9		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/The_Gate_Chamber\">The Gate Chamber</a>																	0	1				9		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\" checked=\"\">\n\
10		<a href=\"http://ddowiki.com/page/The_Giants%27_Supplies\">The Giants\' Supplies</a>														0	1				0		House Phiarlan - Threnal			The Ruins of Threnal			-																																														-	<input type=\"checkbox\">\n\
10		<a href=\"http://ddowiki.com/page/The_Chamber_of_Rahmat\">The Chamber of Rahmat</a>															0	1				15		Menechtarun							Demon Sands						-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/The_Enemy_Within\">The Enemy Within</a>																	0	1				24		House Jorasco						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
11		<a href=\"http://ddowiki.com/page/Dreams_of_Insanity\">Dreams of Insanity</a>																0	1				18		House Jorasco						Free to Play					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
11		<a href=\"http://ddowiki.com/page/And_the_Dead_Shall_Rise...\">And the Dead Shall Rise...</a>												0	1				18		House Jorasco - Delera\'s Tomb		Delera\'s Tomb					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
11		<a href=\"http://ddowiki.com/page/From_Beyond_the_Grave\">From Beyond the Grave</a>															0	1				15		House Jorasco - Delera\'s Tomb		Delera\'s Tomb					-																																														-	<input type=\"checkbox\" checked=\"\">\n\
11		<a href=\"http://ddowiki.com/page/Made_to_Order\">Made to Order</a>																			0	1				18		House Kundarak						Free to Play					-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/The_Spawn_of_Whisperdoom\">The Spawn of Whisperdoom</a>													0	1				18		House Phiarlan						Free to Play					-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/Tomb_of_the_Blighted\">Tomb of the Blighted</a>															0	8				18		House Phiarlan - The Necropolis		The Necropolis, Part 3			-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/Tomb_of_the_Forbidden\">Tomb of the Forbidden</a>															0	24				18		House Phiarlan - The Necropolis		The Necropolis, Part 3			-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/Tomb_of_the_Tormented\">Tomb of the Tormented</a>															0	26.5			18		House Phiarlan - The Necropolis		The Necropolis, Part 3			-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/Tomb_of_the_Unhallowed\">Tomb of the Unhallowed</a>														0	10.5			18		House Phiarlan - The Necropolis		The Necropolis, Part 3			-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/Desert_Caravan\">Desert Caravan</a>																		0	1				15		House Phiarlan / Menechtarun		Demon Sands						-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/An_Offering_of_Blood\">An Offering of Blood</a>															0	1				24		Menechtarun							Demon Sands						-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/Maraud_the_Mines\">Maraud the Mines</a>																	0	1				18		Menechtarun							Demon Sands						-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/Purge_the_Fallen_Shrine\">Purge the Fallen Shrine</a>														0	1				18		Menechtarun							Demon Sands						-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/Raid_the_Vulkoorim\">Raid the Vulkoorim</a>																0	1				18		Menechtarun							Demon Sands						-																																														-	<input type=\"checkbox\">\n\
11		<a href=\"http://ddowiki.com/page/The_Chamber_of_Kourush\">The Chamber of Kourush</a>														0	1				18		Menechtarun							Demon Sands						-																																														-	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/Invaders!\">Invaders!</a>																					0	1				21		Harbor								Free to Play					-																																														-	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/A_Relic_of_a_Sovereign_Past\">A Relic of a Sovereign Past</a>												0	1				21		House Deneith / House Kundarak		Free to Play					-																																														-	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/The_Cursed_Crypt\">The Cursed Crypt</a>																	0	25				21		House Phiarlan - The Necropolis		The Necropolis, Part 3			-																																														-	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/Against_the_Demon_Queen_(quest)\">Against the Demon Queen</a>												0	1				24		Menechtarun							Demon Sands						-																																														Pre-raid: Zawabi\'s Revenge (Once per raid)	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/The_Chamber_of_Raiyum\">The Chamber of Raiyum</a>															0	1				24		Menechtarun							Demon Sands						-																																														-	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/Chains_of_Flame\">Chains of Flame</a>																		0	1				21		Menechtarun							Demon Sands						-																																														-	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/Zawabi%27s_Revenge\">Zawabi\'s Revenge</a>																0	1				18		Menechtarun							Demon Sands						-																																														Raid	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/Diplomatic_Impunity\">Diplomatic Impunity</a>																0	1				18		The Twelve - Lordsmarch Plaza		Free to Play					-																																														-	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/Eyes_of_Stone\">Eyes of Stone</a>																			0	1				18		The Twelve - Lordsmarch Plaza		Free to Play					-																																														-	<input type=\"checkbox\">\n\
12		<a href=\"http://ddowiki.com/page/Frame_Work\">Frame Work</a>																				0	1				15		The Twelve - Lordsmarch Plaza		Free to Play					-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/A_Cry_for_Help\">A Cry for Help</a>																		0	1				21		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/Feast_or_Famine\">Feast or Famine</a>																		0	1				18		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/Foundation_of_Discord\">Foundation of Discord</a>															0	1				18		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/The_Maze_of_Madness\">The Maze of Madness</a>																0	1				18		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/Trial_by_Fire\">Trial by Fire</a>																			0	1				18		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/Memoirs_of_an_Illusory_Larcener\">Memoirs of an Illusory Larcener</a>										0	1				18		Harbor								Free to Play					-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/Mired_in_Kobolds\">Mired in Kobolds</a>																	0	1				15		The Twelve							Free to Play					-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/Siegebreaker\">Siegebreaker</a>																			0	1				18		The Twelve - Lordsmarch Plaza		Attack on Stormreach			-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/Assault_on_Summerfield\">Assault on Summerfield</a>														0	1				15		The Twelve - Lordsmarch Plaza		Attack on Stormreach			-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/Blockade_Buster\">Blockade Buster</a>																		0	1				15		The Twelve - Lordsmarch Plaza		Attack on Stormreach			-																																														-	<input type=\"checkbox\">\n\
13		<a href=\"http://ddowiki.com/page/Undermine\">Undermine</a>																					0	1				15		The Twelve - Lordsmarch Plaza		Attack on Stormreach			-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/Madstone_Crater\">Madstone Crater</a>																		0	1				24		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/The_Crucible\">The Crucible</a>																			0	1				24		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/Gianthold_Tor\">Gianthold Tor</a>																			0	1				21		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/A_Cabal_for_One\">A Cabal for One</a>																		0	1				18		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/The_Prison_of_the_Planes\">The Prison of the Planes</a>													0	1				18		Gianthold							Ruins of Gianthold				-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/The_Reaver%27s_Fate\">The Reaver\'s Fate</a>																0	1				18		Gianthold							Ruins of Gianthold				-																																														Raid	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/Desecrated_Temple_of_Vol\">Desecrated Temple of Vol</a>													0	1				18		House Phiarlan - The Necropolis		The Necropolis, Part 4			-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/Flesh_Maker%27s_Laboratory\">Flesh Maker\'s Laboratory</a>												0	1				18		House Phiarlan - The Necropolis		The Necropolis, Part 4			-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/Ghosts_of_Perdition\">Ghosts of Perdition</a>																0	1				18		House Phiarlan - The Necropolis		The Necropolis, Part 4			-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/Inferno_of_the_Damned\">Inferno of the Damned</a>															0	1				18		House Phiarlan - The Necropolis		The Necropolis, Part 4			-																																														-	<input type=\"checkbox\">\n\
14		<a href=\"http://ddowiki.com/page/Tower_of_Frost\">Tower of Frost</a>																		0	1				15		Marketplace							Free to Play					-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Disciples_of_Shar\">Disciples of Shar</a>																	0	1				18		Eveningstar							Free to Play					-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Search_and_Rescue\">Search and Rescue</a>																	0	1				18		Eveningstar							Free to Play					-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Escape_Plan\">Escape Plan</a>																				0	1				15		Eveningstar							Free to Play					-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Desire_in_the_Dark\">Desire in the Dark</a>																0	1				15		Eveningstar - Tethyamar				The Mines of Tethyamar			-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Graveyard_Shift\">Graveyard Shift</a>																		0	1				15		Eveningstar - Tethyamar				The Mines of Tethyamar			-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Records_of_the_Past\">Records of the Past</a>																0	1				15		Eveningstar - Tethyamar				The Mines of Tethyamar			-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Strike_Back\">Strike Back</a>																				0	1				15		Eveningstar - Tethyamar				The Mines of Tethyamar			-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Third_Time%27s_a_Charm\">Third Time\'s a Charm</a>														0	1				15		Eveningstar - Tethyamar				The Mines of Tethyamar			-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Shadow_of_a_Doubt\">Shadow of a Doubt</a>																	0	1				18		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Litany_of_the_Dead\">Litany of the Dead</a>																0	1				18		House Phiarlan - The Necropolis		The Necropolis, Part 4			-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Creeping_Death\">Creeping Death</a>																		0	1				18		Meridia								The Vale of Twilight			-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/To_Curse_the_Sky\">To Curse the Sky</a>																	0	1				18		Meridia								The Vale of Twilight			Elite: Abishai/Bearded Devil: 50 Good; Orthon/Erinyes/Hellcat: 52 Good; Nal\'thera 57 Good; Malicia 55 Good																				1500 Exp Rescue Archons; 890 Exp kill Nal\'thera	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Acid_Wit\">Acid Wit</a>																					0	1				18		The Twelve							Free to Play					-																																														-	<input type=\"checkbox\">\n\
15		<a href=\"http://ddowiki.com/page/Delirium\">Delirium</a>																					0	1				15		The Twelve							Free to Play					-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/The_Mask_of_Deception\">The Mask of Deception</a>															0	1				18		Eveningstar							Free to Play					-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/A_Lesson_in_Deception\">A Lesson in Deception</a>															0	1				21		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/Army_of_Shadow\">Army of Shadow</a>																		0	1				21		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/Friends_in_Low_Places\">Friends in Low Places</a>															0	1				21		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/Through_a_Mirror_Darkly\">Through a Mirror Darkly</a>														0	1				21		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/The_Thrill_of_the_Hunt\">The Thrill of the Hunt</a>														0	1				18		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/Beyond_the_Rift\">Beyond the Rift</a>																		0	1				21		Harbor								Free to Play					-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/Servants_of_the_Overlord\">Servants of the Overlord</a>													0	1				21		Harbor								Free to Play					-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/The_Lords_of_Dust\">The Lords of Dust</a>																	0	1				21		Harbor								Free to Play					-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/The_Spinner_of_Shadows\">The Spinner of Shadows</a>														0	1				21		Harbor								Free to Play					-																																														-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/Let_Sleeping_Dust_Lie\">Let Sleeping Dust Lie</a>															0	1				24		Meridia								The Vale of Twilight			Elite: Rakshasa: 15 Good 15 Pierce; Named Rakshasas: 20 Good 20 Pierce																													Orange backwards F, Red =|=, Blue H.	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/Rainbow_in_the_Dark\">Rainbow in the Dark</a>																0	1				24		Meridia								The Vale of Twilight			Elite: Earth Elemental 10 -; Stone Golem 15 Adamant; Orthon/Bearded Devil: 15 Good/Silver; Agorthony: 20 Good/Silver																	Search DCs for hidden doors (Elite): 31-32, 37, 32	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/Ritual_Sacrifice\">Ritual Sacrifice</a>																	0	1				24		Meridia								The Vale of Twilight			Elite: Bearded Devil/Orthon/Bezekira: 15 Good; Crean: 25 Good; Elementals: 10-; Ancient Air Elementals: 15-																				-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/Running_with_the_Devils\">Running with the Devils</a>														0	1				24		Meridia								The Vale of Twilight			Elite: Eladrin/Ghaele: 15 Cold Iron; Bralani: 15 Evil; Taeron Rimond: 15 Cold Iron/Evil; Bearded Devil: 15 Good/Silver; Nosrat/Tazful/Bairger: 20 Good/Silver; Odaka: 20 Good/Silver	-	<input type=\"checkbox\">\n\
16		<a href=\"http://ddowiki.com/page/The_Coalescence_Chamber\">The Coalescence Chamber</a>														0	1				24		Meridia								The Vale of Twilight			-																																														-	<input type=\"checkbox\">\n\
17		<a href=\"http://ddowiki.com/page/Good_Intentions\">Good Intentions</a>																		0	1				21		Harbor								Free to Play					-																																														-	<input type=\"checkbox\">\n\
17		<a href=\"http://ddowiki.com/page/Ascension_Chamber\">Ascension Chamber</a>																	0	1				21		House Phiarlan - The Necropolis		The Necropolis, Part 4			-																																														Raid	<input type=\"checkbox\">\n\
17		<a href=\"http://ddowiki.com/page/The_Shroud\">The Shroud</a>																				0	1				33		Meridia								The Vale of Twilight			-																																														Raid	<input type=\"checkbox\">\n\
17		<a href=\"http://ddowiki.com/page/Enter_the_Kobold\">Enter the Kobold</a>																	0	1				24		Reaver\'s Refuge					The Reaver\'s Reach				-																																														-	<input type=\"checkbox\">\n\
17		<a href=\"http://ddowiki.com/page/Monastery_of_the_Scorpion\">Monastery of the Scorpion</a>													0	1				24		Reaver\'s Refuge					The Reaver\'s Reach				-																																														-	<input type=\"checkbox\">\n\
17		<a href=\"http://ddowiki.com/page/Prey_on_the_Hunter\">Prey on the Hunter</a>																0	1				24		Reaver\'s Refuge					The Reaver\'s Reach				-																																														-	<input type=\"checkbox\">\n\
17		<a href=\"http://ddowiki.com/page/Stealer_of_Souls\">Stealer of Souls</a>																	0	1				24		Reaver\'s Refuge					The Reaver\'s Reach				-																																														-	<input type=\"checkbox\">\n\
18		<a href=\"http://ddowiki.com/page/Dream_Conspiracy\">Dream Conspiracy</a>																	0	1				18		Harbor - The Inspired Quarter		The Path of Inspiration			-																																														-	<input type=\"checkbox\">\n\
18		<a href=\"http://ddowiki.com/page/Finding_the_Path\">Finding the Path</a>																	0	1				18		Harbor - The Inspired Quarter		The Path of Inspiration			-																																														-	<input type=\"checkbox\">\n\
18		<a href=\"http://ddowiki.com/page/I_Dream_of_Jeets\">I Dream of Jeets</a>																	0	1				18		Harbor - The Inspired Quarter		The Path of Inspiration			-																																														-	<input type=\"checkbox\">\n\
18		<a href=\"http://ddowiki.com/page/In_the_Demon%27s_Den\">In the Demon\'s Den</a>															0	1				18		Harbor - The Inspired Quarter		Free to Play					Elite: Aurora: 22 Good 22 Cold Iron; others as well																																		With 2: Split North and South, lure to center while one goes to finish last	<input type=\"checkbox\">\n\
18		<a href=\"http://ddowiki.com/page/The_Mindsunder\">The Mindsunder</a>																		0	1				18		Harbor - The Inspired Quarter		The Path of Inspiration			-																																														-	<input type=\"checkbox\">\n\
18		<a href=\"http://ddowiki.com/page/The_Shipwrecked_Spy\">The Shipwrecked Spy</a>																0	1				18		Harbor - The Inspired Quarter		The Path of Inspiration			-																																														-	<input type=\"checkbox\">\n\
18		<a href=\"http://ddowiki.com/page/A_Vision_of_Destruction\">A Vision of Destruction</a>														0	1				27		Marketplace - The Subterrane		The Vale of Twilight			-																																														Raid	<input type=\"checkbox\">\n\
18		<a href=\"http://ddowiki.com/page/Hound_of_Xoriat\">Hound of Xoriat</a>																		0	1				27		Marketplace - The Subterrane		The Vale of Twilight			-																																														Raid	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/A_Break_in_the_Ice\">A Break in the Ice</a>																0	1				21		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/The_Riddle\">The Riddle</a>																				0	1				21		Eveningstar?						Menace of the Underdark			-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/What_Goes_Up\">What Goes Up</a>																			0	1				21		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Breaking_the_Ranks\">Breaking the Ranks</a>																0	1				18		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Lines_of_Supply\">Lines of Supply</a>																		0	1				18		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Murder_by_Night\">Murder by Night</a>																		0	1				18		Eveningstar?						Menace of the Underdark			-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/The_Tracker%27s_Trap\">The Tracker\'s Trap</a>															0	1				18		Eveningstar?						Shadowfell Conspiracy			-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Eye_of_the_Titan\">Eye of the Titan</a>																	0	1				18		Harbor - The Inspired Quarter		The Dreaming Dark				-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Mining_for_Ancient_Secrets\">Mining for Ancient Secrets</a>												0	1				18		Harbor - The Inspired Quarter		The Dreaming Dark				-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Reclaiming_Memories\">Reclaiming Memories</a>																0	1				18		Harbor - The Inspired Quarter		The Dreaming Dark				-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Raiding_the_Giants%27_Vault\">Raiding the Giants\' Vault</a>												0	1				6		Harbor - The Inspired Quarter		The Dreaming Dark				-																																														-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Genesis_Point\">Genesis Point</a>																			0	1				24		Shavarath							The Devils of Shavarath			Elite: Barbazu/Orthon: 15 Good																																							-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/A_New_Invasion\">A New Invasion</a>																		0	1				21		Shavarath							The Devils of Shavarath			Elite: Barbazu/Orthon: 15 Good; Iron Golem 15 Adamant; Clay Golem 10 Adamant; Earth Elemental: 25 Adamant 10 -; All Elementals: 10-, Barnzidu 20 Good 20 Silver							-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Bastion_of_Power\">Bastion of Power</a>																	0	1				21		Shavarath							The Devils of Shavarath			Elite: Barbazu/Orthon: 15 Good; Bezekira 30 Good; Erisandes 20 Good 20 Silver; Keradi 15 Good 15 Cold Iron; Hezrou 20 Good; Jaralith 15 Cold Iron										2 levers to open stairs at central South, exit upstairs on Southwest. Second area: exit upstairs on Southeast	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Sins_of_Attrition\">Sins of Attrition</a>																	0	1				21		Shavarath							The Devils of Shavarath			Elite: Barbazu/Orthon: 15 Good; Cinderspawn/Elemental: 10-;																																-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/The_Weapons_Shipment\">The Weapons Shipment</a>															0	1				18		Shavarath							The Devils of Shavarath			Elite: Barbazu/Orthon: 15 Good; Bezekira 30 Good; Succubus 10 Good; Gorgith-Tor 20 Good 20 Silver																						-	<input type=\"checkbox\">\n\
19		<a href=\"http://ddowiki.com/page/Wrath_of_the_Flame\">Wrath of the Flame</a>																0	1				18		Shavarath							The Devils of Shavarath			Elite: Succubus: 10 Good; Barbazu/Orthon: 15 Good; Malicia/Red Named Succubi: 20 Good; Bezekira: 30 Good																				-	<input type=\"checkbox\">\n\
20		<a href=\"http://ddowiki.com/page/The_Dreaming_Dark_(quest)\">The Dreaming Dark</a>															0	1				18		Harbor - The Inspired Quarter		The Dreaming Dark				-																																														-	<input type=\"checkbox\">\n\
20		<a href=\"http://ddowiki.com/page/Tower_of_Despair\">Tower of Despair</a>																	0	1				24		Shavarath							The Devils of Shavarath			-																																														Raid	<input type=\"checkbox\">\n\
";
